### ISSUE TITLE
Trojan Detected

### ISSUE THREAD

**Issue by nerdybails** [justin025/onthespot#10]
Defender detects a trojan in this release (v0.7.0)

![Screenshot 2024-09-26 140521](https://github.com/user-attachments/assets/b528d9df-fbf2-434a-b032-173f779a5fe0)

**Comment by justin025** [comment]
I have no idea how to fix this, I am assuming its because your downloaded file is listed as an exe.exe which is weird, I do remember the old onthespot had similar false positives. 

Here is a scan for the 0.7.0 release on virus total:
https://www.virustotal.com/gui/url/96d45433e6b8a54e9b97e61cae795fc650dedff12edd0e0ebf4fc753121394e5?nocache=1

The test build for 0.7.1 is not listed as a virus if you would like to download it instead
https://github.com/justin025/onthespot/releases/download/dev/OnTheSpot.exe

https://www.virustotal.com/gui/url/5d1e75088e6dc9bdbc330ec2304a0c599ef796b185066946ee3fe353feeff9e4?nocache=1

**Comment by nerdybails** [comment]
Yeah super odd, I scanned it in paid Malwarebytes and no virus. Might just be Defenders "AI scanning" being overly aggressive.

**Comment by justin025** [comment]
Defender has in the past been known to mark piracy tools as a virus. Glad malwarebytes seems fine.
