### ISSUE TITLE
Downloads failing Mac OSX M3 Pro

### ISSUE THREAD

**Issue by Rowleys** [justin025/onthespot#14]
Hi. Really good software. when it was working.

I downloaded half a play list then it just fails all the downloads now . 

I have restarted and relinked. 

Thanks

**Comment by Rowleys** [comment]
Just to add. When I'm looking at Spotify on the desktop app. Its just says connecting to OnTheSpot & in the app it says connected

**Comment by justin025** [comment]
The playlist failing may be due to a rate limit, see [here](https://github.com/justin025/onthespot/issues/3). How many songs are in your playlist, if it is a rate limit it will likely only last 10-15 minutes.

As for spotify saying 'connecting' you can just close and reopen the app, thats known to happen.

If you don't mind me asking, how did you launch the app on an M3 Pro?

**Comment by Rowleys** [comment]
how do you mean open the app? 

I just installed the dmg and clicked it ?

also the playlist have about 40 / 50 tracks in

**Comment by V1p3rOne** [comment]
Could you please provide us the playlist link?

**Comment by justin025** [comment]
Most likely a rate limit issue, set download delay to 35 seconds and you will not have failed songs, for more info see https://github.com/justin025/onthespot/issues/3.
