### ISSUE TITLE
Login without Spotify Desktop

### ISSUE THREAD

**Issue by peterpepo** [justin025/onthespot#37]
### Feature Description

Hello is there a way to log in without running a spotify desktop app?
In the original onthespot, adding email/password directly did work fine.

### Justification

Don't want nor need to install spotify desktop client on my debian machine.
I listen regularly via browser player, so no need for desktop app.

**Comment by justin025** [comment]
Spotify depreciated email/password login in the api which is why the fork came to be in the first place. I hate installing the spotify desktop app on my linux box aswell but its just one of those things you have to put up with to login. Once the credentials are generated they're valid until you change your password.

In theory the login mechanism could switch to sc_dc and sc_key in your spotify web browser session cache but this would scare away many non technical users so I think i'd prefer to avoid it for now.

**Comment by peterpepo** [comment]
Ah, this is the thing. I've had my original onthespot installed and logged in for months now, because I didn't change my password and thus didn't need to relogin.

Thanks for this awesome fork anyway. Just download & run (&put ffmpeg in directory, or add it to path).

Thanks for your answer and attitude too. Explaining why/not the feature can/not be implemented 👍
