### ISSUE TITLE
Metadata update for previous downloads

### ISSUE THREAD

**Issue by chalda** [justin025/onthespot#38]
### Feature Description

update metadata on files downloaded with previous version. 
could be a script as well. 

### Justification

easier to switch to the fork without redownloading everything

### Additional Information

none

**Comment by justin025** [comment]
you said your old files contain the internal spotify uri (i believe). You could write a script to fetch your api key, use mutagen to check if the uri exists and if it does parse it and fill in missing fields en mass. I will not add a feature like this to the app but I can add a checkbox to check if the file exists and if so reembed metadata, cover, lyrics and exit. Does this work for you? If your collection is too large to requeue a script might be best.

**Comment by chalda** [comment]
That’s exactly what I am looking for!

started looking at the code yesterday to see how easy it is to do but it
seemed like you’d have to redownload the file to be able to get the id3
tags. Or is there a way without refetching the file? Not sure how common it
is for applications to only look up metadata either, but I’d rather not
redownload the actual blob if I don’t have to.

I guess the only issue is then file/folder naming conventions. The old
default is /artist/album/title-artist.mp3 iirc.

You only do a check by file name and don’t maintain a database right? There
is a case to be made for having a database keyed by trackname as with the
folder and name convention I just mentioned you end up getting a lot of
dupes because the same track can be in an EP LP and compilations but since
these are all different artist and albums it will not collide based on file
path lookups alone.

**Comment by justin025** [comment]
check this, just call the following and the file will be tagged
https://github.com/justin025/onthespot/blob/12460badd9e0a0f9d1685eec4d2dcd1731fb6bc8/src/onthespot/downloader.py#L213-L233

You just need to add those lines under already exists and the app will do the rest
https://github.com/justin025/onthespot/blob/12460badd9e0a0f9d1685eec4d2dcd1731fb6bc8/src/onthespot/downloader.py#L135-L142

If i get to this it will probably look like, 
```python
if config.get('embed_if_exists'):
    ..add tags
    continue

**Comment by 0rkaM** [comment]
@chalda about the following:
> I guess the only issue is then file/folder naming conventions. The old
> default is /artist/album/title-artist.mp3 iirc.
> 
> You only do a check by file name and don’t maintain a database right? There
> is a case to be made for having a database keyed by trackname as with the
> folder and name convention I just mentioned you end up getting a lot of
> dupes because the same track can be in an EP LP and compilations but since
> these are all different artist and albums it will not collide based on file
> path lookups alone.

Is this about having dupe songs that may or may not be exact, just because of them been released in multiple editions?
Or is this having dupes because of the changes in the Path naming that we had though different versions?
And in either case what is your suggestion to or how you actually handling it?

And @justin025 if adding some code would resolve (retag) the past songs, I would be all for it... Just don't know what the proper way would be to add or edit the tags, as of the latest version.

Since is not a finalized product, I created a specific folder for all the download from OtS separated from all the other music I have and for the short time I am using I already have a lot of dupes, since we first used as root Artist_Name;Other_Names and then for a short time we had just Artist_Name and now we have again Artist_Name;Other_Names, but slightly different, so as of today I have many dupes and some triplets of the songs.

I know it can be hard to vote, or decide what would be the proper tagging and path naming to follow for now to the for the foreseeable future, so I think having an easy way to re-tag all the files would be good.

**Comment by justin025** [comment]
> I know it can be hard to vote, or decide what would be the proper tagging and path naming to follow

If you would like to change the old naming convention to the new one you can use a program like mp3tag which allows you to organize your music library based on the metadata, say move all tracks with the same artist into an {artist} folder. This way you don't have to worry about setting things just right as you can fix up all your directories at a later date.

> Just don't know what the proper way would be to add or edit the tags, as of the latest version.

Opted to use mutagen to tag songs instead of a wrapper as in the old application for better compatibility. You can check the function set_audio_tags in post-download.py  its as simple as calling the item_metadata and feeding it in. If you want an example on how the library works you can check this for a quick overview https://stackoverflow.com/questions/42231932/writing-id3-tags-using-easyid3

If you have any further questions feel free to let me know

**Comment by 0rkaM** [comment]
@justin025 thank you, I forgot about MP3Tag, it was a very nice program, and now after you reminded me, I checked, and it has gotten even better.
But I am also curious, so I am also going to check set_audio_tags in post-download.py and read about the mutagen library, thanks.
Cheers

**Comment by justin025** [comment]
Added this in the latest commit, just a matter of checking Overwrite Existing Collection under Metadata.

It _should_ clear existing metadata and then rewrite the tags and thumbnail.

**Comment by 0rkaM** [comment]
I am on the latest 1.0.2... where is this option again?

**Comment by justin025** [comment]
1.0.3 marked as prerelease. Also fixes all the m3u issues, sorry about all that

**Comment by chalda** [comment]
Hate you necro a closed thread but life really been kicking me in the balls last 6 months, catching up on stuff.
Really appreciated your updates btw! 

Ran into this other project last night, not sure how i never knew about it:
https://github.com/Marekkon5/onetagger
Useful to deal with the exact issue of wanting to sync/fix tags but without redownloading the entire library. Would make the transition less painful and easier on networks/drives.

Not guaranteed that ISRC tag is there but i am sure with a few changes can prolly use the spotID comment instead. 
Might even make sense to run an external script and update the ISRC tag first as a pre-step.

Def need some sort of DB or ORM of sort, as a slight metadata change like order of Artists swapping results a naming convention like  {Artist} - {Title} introduce tons of dups. Saw you also added a CLI,  might make sense to use OTS as an external plugin and manage  stuff in MusicBee or somesuch. 

Kudos btw, single handedly propelled the app years into the future in a few few months! (or years from the past into the here and now haha!)
