### ISSUE TITLE
Playlist save dir

### ISSUE THREAD

**Issue by guglielmoTaro** [justin025/onthespot#4]
At this moment the download dir pattern is unique between tracks/albums and playlists, making it so that downloading a playlist spawns several album folders.
on th other hand, specifiyng only the playlist name as download dir leaves albums without a path to download.
would it be feasible to provide two different destinations for playlists and albums/tracks?

**Comment by justin025** [comment]
If I'm understanding correctly the logic you are requesting is something like if playlist_name is empty then use a different download path. 

One possible solution is to use the temporary download path under the search field while downloading playlists.

Otherwise I could add a box to advanced settings to download somewhere else if playlist_name is empty but it might take a few days / a week because I'm a little busy at the moment.

If this is a feature you'd really like let me know.

**Comment by zerog13** [comment]
for playlists, i've been downloading them, searching for *.mp3, moving them to a new folder with the correct name. downside is you can't be downloading other artists otherwise they can get mixed up. But it's easy to move all your downloads, download the playlist, move the playlist tracks, and get back to straight artists.
