### ISSUE TITLE
successfully downloaded  tracks are displayed as failed

### ISSUE THREAD

**Issue by WolfgangDpunkt** [justin025/onthespot#91]
Hey,

I am back. :-)
I think there is a new bug, possibly in connection with the Retry Worker?

When downloading, finished tracks are successfully downloaded (I see them in the download directory, they contain the correct audio data), but the app displays the track as failed and deletes the file in the download directory before continuing.
I tried it with enabled and disabled Retry-Worker-feature, no difference.

This version I used:
https://github.com/justin025/onthespot/actions/runs/12524588316

Here is my log:
[onthespot.log](https://github.com/user-attachments/files/18266372/onthespot.log)

**Comment by justin025** [comment]
This error is not with the retry worker. If you have 'Save Album Cover' disabled it will try to delete cover.png before proceeding, and if it cannot delete cover.png it will delete your download because maybe its corrupted or did not receive its thumbnail.

here is the error in your log
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Wolfgangd/Downloads/Hoerbools/Tracks/Adalbert Stifter/[2023] Bergmilch/cover.png'

I found something in the code that might be the problem and pushed a commit now, your issue should be fixed. If not let me know

**Comment by WolfgangDpunkt** [comment]
Thanks, the new version has fixed this bug.
Now it works perfectly for me :-)
Thank you.
